import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>YNSF REGISTRASI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="homeregist-section">
        <div className="wrapper">
          <div className="">
            <h2 className="">FORMULIR REGISTRASI</h2>
            <h1 className="">Registrasi YNSF</h1>
          </div>
        </div>

        <div className="wrapper">
          <Link href="/indonesiaparticipants" legacyBehavior>
            <a
              className="btn btn-custom text-center mt-5"
            >
              Peserta Indonesia{" "}
              <i className="fa-solid fa-earth-americas"></i>
            </a>
          </Link>
        </div>
      </section>
    </>
  );
}
